=== youssefashraf1/MaintenanceProject/Documentation/Interfaces/StudentStatuses.dtd
<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
 
<!ELEMENT studentStatuses ( status+ ) >
<!ATTLIST studentStatuses created CDATA #IMPLIED >
<!ATTLIST studentStatuses dateFormat CDATA #IMPLIED >
<!ATTLIST studentStatuses timeFormat CDATA #IMPLIED >
<!ATTLIST studentStatuses incremental (true|false) "true">
 
<!ELEMENT status ( permissions, effective-dates?, message?, course*, fallback? ) >
<!ATTLIST status reference CDATA #REQUIRED >
<!ATTLIST status name CDATA #REQUIRED >
<!ATTLIST status session (true|false) "false">

<!ELEMENT permissions EMPTY >
<!ATTLIST permissions assistantEnabled (true|false) "false">
<!ATTLIST permissions assistantAdminEdit (true|false) "false">
<!ATTLIST permissions assistantAdvisorEdit (true|false) "false">
<!ATTLIST permissions assistantStudentEdit (true|false) "false">
<!ATTLIST permissions requestsEnabled (true|false) "false">
<!ATTLIST permissions requestsAdminEdit (true|false) "false">
<!ATTLIST permissions requestsAdvisorEdit (true|false) "false">
<!ATTLIST permissions requestsStudentEdit (true|false) "false">
<!ATTLIST permissions emaiNotifications (true|false) "false">
<!ATTLIST permissions doNotScheduleInBatch (true|false) "false">
<!ATTLIST permissions mustHaveCourseType (true|false) "false">
<!ATTLIST permissions waitListing (true|false) "false">
<!ATTLIST permissions advisorCanSetStatus (true|false) "false">

<!ELEMENT effective-dates EMPTY >
<!ATTLIST effective-dates startDate CDATA #IMPLIED >
<!ATTLIST effective-dates startPeriod CDATA #IMPLIED >
<!ATTLIST effective-dates stopDate CDATA #IMPLIED >
<!ATTLIST effective-dates stopPeriod CDATA #IMPLIED >

<!ELEMENT message (#PCDATA) >

<!ELEMENT course EMPTY >
<!ATTLIST course type CDATA #REQUIRED >

<!ELEMENT fallback EMPTY >
<!ATTLIST fallback reference CDATA #REQUIRED >

=== youssefashraf1/MaintenanceProject/Documentation/Interfaces/Examples/studentStatuses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentStatuses PUBLIC "-//UniTime//UniTime Student Scheduling Statuses DTD/EN" "http://www.unitime.org/interface/StudentStatuses.dtd">

<!-- 
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 -->
<studentStatuses created="Tue Apr 03 15:06:12 CEST 2018" dateFormat="yyyy/M/d" timeFormat="HHmm" incremental="true">
  <status reference="Disabled" name="Access disabled">
    <permissions assistantEnabled="false" assistantAdvisorEdit="false" emaiNotifications="true" mustHaveCourseType="false" waitListing="false" doNotScheduleInBatch="false" assistantStudentEdit="false" assistantAdminEdit="false" requestsStudentEdit="false" requestsEnabled="false" requestsAdvisorEdit="false" requestsAdminEdit="false" advisorCanSetStatus="true"/>
  </status>
  <status reference="Enabled" name="Access enabled">
    <permissions assistantEnabled="true" assistantAdvisorEdit="true" emaiNotifications="true" mustHaveCourseType="false" waitListing="false" doNotScheduleInBatch="false" assistantStudentEdit="true" assistantAdminEdit="true" requestsStudentEdit="true" requestsEnabled="true" requestsAdvisorEdit="true" requestsAdminEdit="true" advisorCanSetStatus="false"/>
  </status>
  <status reference="Enrollment" name="Scheduling Assistant Enabled">
    <permissions assistantEnabled="true" assistantAdvisorEdit="true" emaiNotifications="true" mustHaveCourseType="false" waitListing="false" doNotScheduleInBatch="false" assistantStudentEdit="true" assistantAdminEdit="true" requestsStudentEdit="false" requestsEnabled="false" requestsAdvisorEdit="false" requestsAdminEdit="false" advisorCanSetStatus="true"/>
    <effective-dates startDate="2018/7/1" stopDate="2018/7/31"/>
    <message>Enrollment is enabled.</message>
    <fallback reference="Disabled"/>
  </status>
  <status reference="No Email" name="Access enabled, no email notification">
    <permissions assistantEnabled="true" assistantAdvisorEdit="true" emaiNotifications="false" mustHaveCourseType="false" waitListing="false" doNotScheduleInBatch="false" assistantStudentEdit="true" assistantAdminEdit="true" requestsStudentEdit="true" requestsEnabled="true" requestsAdvisorEdit="true" requestsAdminEdit="true" advisorCanSetStatus="false"/>
  </status>
  <status reference="Not Available" name="Temporarily not available">
    <permissions assistantEnabled="true" assistantAdvisorEdit="true" emaiNotifications="true" mustHaveCourseType="false" waitListing="false" doNotScheduleInBatch="false" assistantStudentEdit="false" assistantAdminEdit="true" requestsStudentEdit="false" requestsEnabled="false" requestsAdvisorEdit="false" requestsAdminEdit="false" advisorCanSetStatus="false"/>
    <message>Access is temporarily disabled. Please try again later...</message>
  </status>
  <status reference="Requests" name="Course Requests Enabled">
    <permissions assistantEnabled="false" assistantAdvisorEdit="false" emaiNotifications="true" mustHaveCourseType="false" waitListing="false" doNotScheduleInBatch="false" assistantStudentEdit="false" assistantAdminEdit="false" requestsStudentEdit="true" requestsEnabled="true" requestsAdvisorEdit="true" requestsAdminEdit="true" advisorCanSetStatus="true"/>
    <effective-dates startDate="2018/4/1" startPeriod="0800" stopDate="2018/5/31" stopPeriod="2200"/>
    <message>Registration is enabled.</message>
    <fallback reference="Disabled"/>
  </status>
</studentStatuses>
